# 自动部署的名称
name: GitHub pages deploy
 
on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:
 
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
 
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 9.1.4
          # 使用 pnpm 安装依赖
          run_install: true
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 18.20.3
          # 缓存 pnpm 依赖
          cache: pnpm
 
      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build
 
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: src/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 部署到服务器
  deploy-server:
    runs-on: ubuntu-latest
    # 确保在部署到 GitHub Pages 之后执行
    needs: deploy-gh-pages
    steps:
      # 检出网站代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 检出 gh-pages 分支
          ref: gh-pages
          # 获取全部的历史提交
          fetch-depth: 0

      # 配置环境
      - name: Configuration environment
        # 写入私钥、配置 Git 用户名，写入服务器地址
        # 您需要自行将服务器的私钥写入 secrets 的 SSH_PRIVATE_KEY
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan <your domain> >> ~/.ssh/known_hosts
          git config --global user.name 'Your Name'
          git config --global user.email 'You email'

      # 部署到服务器
      - name: Deploy
        # 使用 Git 将网站代码强制推送到远程的网站目录
        # 并使用 SSH 连接服务器进入网站目录手动切换到最新提交
        run: |
          git push -f git@<your domain>:<deploy dir> gh-pages
          ssh git@<your domain> "cd <deploy dir> && git reset --hard HEAD"