name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # main分支，你也可以改成其他分支
      - main
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        # 使用action库  actions/setup-node安装node
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
          run_install: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 18.20.3
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build

      # 部署到阿里云
      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0.2 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }} # 引用配置，SSH私钥
          ARGS: -e -c -r --delete --exclude=*.pyc # rsync参数，排除.pyc文件
          SERVER_PORT: ${{ secrets.SERVER_PORT }} # SSH端口
          FOLDER: "./src/.vuepress/dist" # 要推送的文件夹，路径相对于代码仓库的根目录，视情况替换为自己的文件夹路径
          SERVER_IP: ${{ secrets.SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.USERNAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /usr/local/tech-knowledge # 部署到目标文件夹